=== about-code/glossarify-md/conf.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/about-code/glossarify-md/v1.0.0/conf.schema.json",
    "type": "object",
    "properties": {
        "baseDir": {
            "description": "Path to directory where to search for the glossary file and markdown files. All paths in a config file will be relative to *baseDir*. *baseDir* itself is relative to the location of the config file or the current working directory when provided via command line. Default is '.'",
            "type": "string",
            "alias": "d",
            "default": "."
        },
        "baseUrl": {
            "description": "The base url to use when creating absolute links to glossary.",
            "type": "string",
            "format": "url",
            "alias": "b",
            "default": "http://127.0.0.1/"
        },
        "excludeFiles": {
            "description": "An array of files or file name patterns that should not be included in any processing.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "alias": "e",
            "default": ["node_modules"]
        },
        "glossaries": {
            "description": "An array of glossaries. Allows for different kinds of glossaries and definitions.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/Glossary"
            },
            "alias": "g",
            "default": [
                { "file": "./glossary.md", "termHint": ""}
            ]
        },
        "ignoreCase": {
            "description": "Find and link every occurrence of a term no matter how it is spelled.",
            "type": "boolean",
            "alias": "i",
            "default": false
        },
        "keepRawFiles": {
            "description": "Glob patterns for (markdown) files to copy from 'baseDir' to 'outDir' but to ignore by the linker. Non-markdown files will be ignored anyways.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "alias": "r",
            "default": []
        },
        "includeFiles": {
            "description": "Path or glob patterns of files to include for linking to glossaries. Default '.' (relative to current working directory).",
            "type": "array",
            "items": {
                "type": "string"
            },
            "alias": "f",
            "default": ["."]
        },
        "linking": {
            "description": "Whether to use relative or absolute links. Default: 'relative'. Choosing 'absolute' requires a 'baseUrl'.",
            "type": "string",
            "enum": [
                "relative",
                "absolute"
            ],
            "alias": "l",
            "default": "relative"
        },
        "outDir": {
            "description": "Path to directory where to write processed files to. Default: './tmp'",
            "type": "string",
            "alias": "o",
            "default": "./tmp"
        },
        "dev": {
            "descriptions": "Options for testing and debugging",
            "$ref": "#/$defs/DevOpts",
            "default": {}
        }
    },
    "$defs": {
        "Glossary": {
            "type": "object",
            "properties": {
                "file": {
                    "description": "Name of the glossary file. Conventional default is 'glossary.md'",
                    "type": "string"
                },
                "termHint": {
                    "description": "A symbol to append to a link to denote that the term refers to a glossary term.",
                    "type": "string"
                }
            }
        },
        "DevOpts": {
            "type": "object",
            "properties": {
                "termsFile": {
                    "description": "File where to write term book to. Enables testing the term extraction results of terminator.",
                    "type": "string"
                },
                "printInputAst": {
                    "description": "Print the AST of scanned markdown documents prior to linkification. May be a Regex to only print AST for particular document.",
                    "type": ["boolean", "string"]
                },
                "printOutputAst": {
                    "description": "Print the AST of scanned markdown documents after linkification. May be a Regex to only print AST for particular document.",
                    "type": ["boolean", "string"]
                }
            }
        }
    }
}

=== about-code/glossarify-md/test/input/features/config-ignoreCase-true/glossarify-md.conf.json
{
    "$schema": "../../../../conf.schema.json",
    "baseDir": ".",
    "linking": "relative",
    "includeFiles": ["."],
    "excludeFiles": [],
    "glossaries": [
        { "file": "./glossary.md"}
    ],
    "ignoreCase": false,
    "outDir": "../../../output-actual/features/config-ignoreCase-true",
    "dev": {
        "termsFile": "../../../output-actual/features/config-ignoreCase-true/terms.json",
        "printInputAst": false,
        "printOutputAst": false
    }
}

=== about-code/glossarify-md/test/input/features/config-glossaries/glossarify-md.conf.json
{
    "$schema": "../../../../conf.schema.json",
    "baseDir": ".",
    "outDir": "../../../output-actual/features/config-glossaries/",
    "includeFiles": ["."],
    "excludeFiles": [
        "**/*exclude*/**"
    ],
    "glossaries": [
        { "file": "./glossary-disjunct-a.md", "termHint": "(a)"},
        { "file": "./glossary-disjunct-b.md", "termHint": "(b)"},
        { "file": "./glossary-common-a.md", "termHint": ""},
        { "file": "./glossary-common-b.md", "termHint": ""}
    ],
    "linking": "relative",
    "ignoreCase": false,
    "dev": {
        "termsFile": "../../../output-actual/features/config-glossaries/terms.json",
        "printInputAst": false,
        "printOutputAst": false
    }
}

=== about-code/glossarify-md/test/input/config-tailored/count-term-occurrences/glossarify-md.conf.json
{
    "$schema": "../../../../conf.schema.json",
    "baseDir": ".",
    "outDir": "../../../output-actual/config-tailored/count-term-occurrences",
    "includeFiles": ["."],
    "excludeFiles": [],
    "keepRawFiles": [],
    "glossaries": [
        { "file": "./glossary.md", "termHint": "" }
    ],
    "linking": "relative",
    "ignoreCase": false,
    "dev": {
        "termsFile": "../../../output-actual/config-tailored/count-term-occurrences/terms.json",
        "printInputAst": false,
        "reproducablePaths": true,
        "printOutputAst": false
    }
}

=== about-code/glossarify-md/test/output-expected/features/config-ignoreCase-true/glossarify-md.conf.json
{
    "$schema": "../../../../conf.schema.json",
    "baseDir": ".",
    "linking": "relative",
    "includeFiles": ["."],
    "excludeFiles": [
        "**/*exclude*/**"
    ],
    "glossaries": [
        { "file": "./glossary.md"}
    ],
    "ignoreCase": true,
    "outDir": "../../../output-actual/features/config-ignoreCase-true",
    "dev": {
        "termsFile": "../../../output-actual/features/config-ignoreCase-true/terms.json",
        "printInputAst": false,
        "printOutputAst": false
    }
}

=== about-code/glossarify-md/test/input/config-tailored/config-linking/absolute-baseUrl/glossarify-md.conf.json
{
    "$schema": "../../../../../conf.schema.json",
    "baseDir": ".",
    "linking": "absolute",
    "baseUrl": "http://localhost",
    "includeFiles": ["."],
    "excludeFiles": [],
    "glossaries": [
        { "file": "./glossary.md" },
        { "file": "./sub-1/glossary.md" }
    ],
    "ignoreCase": false,
    "outDir": "../../../../output-actual/features/config-linking/absolute-baseUrl",
    "dev": {
        "termsFile": "../../../../output-actual/features/config-linking/absolute-baseUrl/terms.json",
        "printInputAst": false,
        "printOutputAst": false
    }
}

=== about-code/glossarify-md/test/input/config-tailored/config-ignoreCase-false/glossarify-md.conf.json
{
    "$schema": "../../../../conf.schema.json",
    "baseDir": ".",
    "linking": "relative",
    "includeFiles": ["."],
    "excludeFiles": [
        "**/*exclude*/**"
    ],
    "glossaries": [
        { "file": "./glossary.md"}
    ],
    "ignoreCase": false,
    "outDir": "../../../output-actual/features/config-ignoreCase-false",
    "dev": {
        "termsFile": "../../../output-actual/features/config-ignoreCase-false/terms.json",
        "printInputAst": false,
        "printOutputAst": false
    }
}

=== about-code/glossarify-md/test/output-expected/config-tailored/config-ignoreCase-false/glossarify-md.conf.json
{
    "$schema": "../../../../conf.schema.json",
    "baseDir": ".",
    "linking": "relative",
    "includeFiles": ["."],
    "excludeFiles": [],
    "glossaries": [
        { "file": "./glossary.md"}
    ],
    "ignoreCase": false,
    "outDir": "../../../output-actual/config-tailored/config-ignoreCase-false",
    "dev": {
        "termsFile": "../../../output-actual/config-tailored/config-ignoreCase-false/terms.json",
        "printInputAst": false,
        "reproducablePaths": true,
        "printOutputAst": false
    }
}

=== about-code/glossarify-md/test/input/config-tailored/config-cli/precedence/glossarify-md.conf.json
{
    "$schema": "../../../../../conf.schema.json",
    "baseUrl": "file://localhost",
    "baseDir": ".",
    "outDir": "../../../../output-actual/config-tailored/config-cli/precedence",
    "includeFiles": ["."],
    "excludeFiles": [],
    "keepRawFiles": [],
    "glossaries": [
        { "file": "./glossary.md", "termHint": ""}
    ],
    "linking": "relative",
    "ignoreCase": false
}
